### ISSUE TITLE
Android + Jack Compiler: NullPointerException

### ISSUE THREAD

**Issue by wa1demar** [requery/requery#344] opened 2016-11-21 08:42 UTC
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformJackWithJackForProdDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.jack.ir.JNodeInternalError: java.lang.Exception: java.lang.NullPointerException
        at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:126)
        at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJackApis(AndroidBuilder.java:1816)
        at com.android.builder.core.AndroidBuilder.convertByteCodeUsingJack(AndroidBuilder.java:1643)
        at com.android.build.gradle.internal.transforms.JackTransform.runJack(JackTransform.java:221)
        at com.android.build.gradle.internal.transforms.JackTransform.transform(JackTransform.java:195)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 15 more
Caused by: com.android.jack.ir.JNodeInternalError: java.lang.Exception: java.lang.NullPointerException
        at com.android.jack.frontend.java.JAstBuilder.handleInternalException(JAstBuilder.java:252)
        at com.android.jack.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:763)
        at com.android.jack.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:460)
        at com.android.jack.frontend.java.JackBatchCompiler.performCompilation(JackBatchCompiler.java:223)
        at com.android.jack.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1712)
        at com.android.jack.frontend.java.JackBatchCompiler.compile(JackBatchCompiler.java:188)
        at com.android.jack.Jack.buildSession(Jack.java:977)
        at com.android.jack.Jack.run(Jack.java:496)
        at com.android.jack.api.v01.impl.Api01ConfigImpl$Api01CompilationTaskImpl.run(Api01ConfigImpl.java:102)
        ... 29 more
Caused by: java.lang.Exception: java.lang.NullPointerException
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
        at com.android.jack.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:909)
        at com.android.jack.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
        ... 35 more
Caused by: java.lang.NullPointerException
        at io.requery.processor.Mirrors.namesEqual(Mirrors.java:159)
        at io.requery.processor.Mirrors.implementsInterface(Mirrors.java:109)
        at io.requery.processor.Mirrors.isInstance(Mirrors.java:91)
        at io.requery.processor.AttributeMember.validateCollectionType(AttributeMember.java:202)
        at io.requery.processor.AttributeMember.checkMemberType(AttributeMember.java:194)
        at io.requery.processor.AttributeMember.process(AttributeMember.java:147)
        at io.requery.processor.EntityType.lambda$process$5(EntityType.java:114)
        at io.requery.processor.EntityType.process(EntityType.java:114)
        at io.requery.processor.EntityProcessor.process(EntityProcessor.java:147)
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
        ... 39 more


BUILD FAILED
```

**Comment by consp1racy** [comment] 2016-11-21 10:20
https://github.com/requery/requery/issues/332

**Comment by Glurt** [comment] 2016-11-21 17:26
Same issue

````
Caused by: java.lang.NullPointerException
	at io.requery.processor.Mirrors.namesEqual(Mirrors.java:159)
	at io.requery.processor.Mirrors.implementsInterface(Mirrors.java:109)
	at io.requery.processor.Mirrors.isInstance(Mirrors.java:91)
	at io.requery.processor.AttributeMember.validateCollectionType(AttributeMember.java:202)
	at io.requery.processor.AttributeMember.checkMemberType(AttributeMember.java:194)
	at io.requery.processor.AttributeMember.process(AttributeMember.java:147)
	at io.requery.processor.EntityType.lambda$process$5(EntityType.java:114)
	at io.requery.processor.EntityType.process(EntityType.java:114)
	at io.requery.processor.EntityProcessor.process(EntityProcessor.java:147)
	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 96 more

**Comment by npurushe** [comment] 2016-11-22 06:40
Which version are you using?

**Comment by Glurt** [comment] 2016-11-25 10:57
Would it be possible to get this in a minor update, I'd like to work on my project over the weekend and this is blocking it.

**Comment by npurushe** [comment] 2016-11-28 05:33
I would recommend using [jitpack](https://jitpack.io/) to consume unreleased versions of master. You can see an example from this [comment](https://github.com/requery/requery/issues/252#issuecomment-254762074). Unfortunately there aren't enough changes on master just yet, thanks

**Comment by wa1demar** [comment] 2016-12-01 13:22
Tried testing new commit - 1a3d5ae

```
Caused by: java.lang.NullPointerException
        at io.requery.processor.EntityGraph.referencingEntity(EntityGraph.java:120)
        at io.requery.processor.EntityGraphValidator.validateEntity(EntityGraphValidator.java:67)
        at io.requery.processor.EntityGraphValidator.validate(EntityGraphValidator.java:50)
        at io.requery.processor.EntityProcessor.process(EntityProcessor.java:156)
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
        ... 93 more


```

**Comment by Glurt** [comment] 2016-12-01 15:24
@wa1demar Did you run into any issues when using jitpack? I've attempted to add the new commits but building fails with:

````
Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.
````

Here's what I have in the gradle file
````
compile 'com.github.requery:requery:requery:1a3d5ae'
compile 'com.github.requery:requery:requery-android:1a3d5ae'
annotationProcessor 'com.github.requery:requery:requery-processor:1a3d5ae'

**Comment by wa1demar** [comment] 2016-12-01 16:01
@Glurt I have no any problem with jitpack. It was used before for another dependencies

**Comment by npurushe** [comment] 2016-12-02 06:06
Probably the dependency change error can be fixed by clearing the gradle cache.

**Comment by wa1demar** [comment] 2016-12-02 08:57
@Glurt You have error in dependency declaration. Shoul be
```
    compile 'com.github.requery.requery:requery:1a3d5ae'
    compile 'com.github.requery.requery:requery-android:1a3d5ae'
    annotationProcessor 'com.github.requery.requery:requery-processor:1a3d5ae'
```

**Comment by wa1demar** [comment] 2016-12-02 09:11
Test result (df38025):

JavaVersion: 1.8
Android compile Sdk Version : 24
Build Tools Version: 24.0.2
Gradle: 2.2.2

```
Caused by: java.lang.NullPointerException
        at io.requery.processor.ElementValidator.lambda$toString$0(ElementValidator.java:100)
        at io.requery.processor.ElementValidator.toString(ElementValidator.java:99)
        at io.requery.processor.EntityProcessor.lambda$process$2(EntityProcessor.java:162)
        at io.requery.processor.EntityProcessor.process(EntityProcessor.java:162)
        at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
        ... 39 more
```

**Comment by wa1demar** [comment] 2016-12-08 14:33
Wow! I have new error:

Commit: 766118c
JavaVersion: 1.8
Android compile Sdk Version : 24
Build Tools Version: 24.0.2
Gradle: 2.2.2

```
Caused by: java.lang.NoSuchMethodException: method definition() does not exist on annotation@io.requery.Column(value = "false")
        at com.android.jack.eclipse.jdt.internal.compiler.apt.model.AnnotationMirrorImpl.invoke(AnnotationMirrorImpl.java:215)
        ... 46 more
```

**Comment by npurushe** [comment] 2016-12-08 16:31
That's caused by using different versions of the `requery-processor` and the main `requery` library, make sure you're using the same version.

**Comment by Glurt** [comment] 2016-12-08 17:20
Commit: 766118c
JavaVersion: 1.8
Android compile Sdk Version : 25
Build Tools Version: 25.0.0
Gradle: 2.2.2

````
Caused by: java.lang.Exception: java.lang.NullPointerException: element == null
	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:169)
	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at com.android.jack.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:909)
	at com.android.jack.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:434)
	... 92 more
Caused by: java.lang.NullPointerException: element == null
	at com.squareup.javapoet.Util.checkNotNull(Util.java:68)
	at com.squareup.javapoet.ClassName.get(ClassName.java:182)
	at io.requery.processor.EntityPartGenerator.parameterizedCollectionName(EntityPartGenerator.java:98)
	at io.requery.processor.EntityMetaGenerator.generateAttribute(EntityMetaGenerator.java:251)
	at io.requery.processor.EntityMetaGenerator.lambda$generate$4(EntityMetaGenerator.java:113)
	at io.requery.processor.EntityMetaGenerator.generate(EntityMetaGenerator.java:86)
	at io.requery.processor.EntityGenerator.generate(EntityGenerator.java:108)
	at io.requery.processor.EntityProcessor.process(EntityProcessor.java:207)
	at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	... 96 more
````

**Comment by npurushe** [comment] 2016-12-15 06:39
An attribute's TypeElement should never be null, this looks like a more fundamental problem with the compiler's implementation of annotation processing right now. Will probably have to wait until it's stabilized.

**Comment by npurushe** [comment] 2017-03-15 03:12
Closing this as Google is ultimately deprecating the Jack toolchain https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html

Note the Android sample app does compile with Jack however Jack still had issues and behavior differences compared to the javac toolchain.

**Closed by npurushe** 2017-03-15 03:12 UTC
Labels: bug
