### ISSUE TITLE
ManyToMany not inserted [Jackson serialization]

### ISSUE THREAD

**Issue by Agraphie** [requery/requery#388] opened 2017-01-02 13:03 UTC
Hi,

I have a question considering the following models. After creating an address and saving it, I create a person and add the previously saved address to its addresses. When saving the person now, no row is inserted into the table `person_address`. Only when I do an update to the previously created address, the row is inserted. Is there a way to prevent this? As the list of addresses is possibly long, I don't want to do a manual update to every address and add all the persons.

```Java
@Entity
public abstract class Person {
  @Key
  int id;

  String name;
  @ManyToMany
  @JunctionTable
  List<AddressEntity> addresses;
}
```

```Java
@Entity
public abstract class Address {
  @Key
  int id;

  String street;
  @ManyToMany
  List<PersonEntity> persons;
}
```

Creation and inserting:
```Java
    AddressEntity address = new AddressEntity();
    address.setId(1);
    address.setStreet("Sesamstreet");
    address.setPersons(new LinkedList<PersonEntity>());
    reactiveEntityStore.insert(address).blockingGet();
    PersonEntity personEntity = new PersonEntity();
    personEntity.setId(2);
    personEntity.setName("Jon Doe");
    List<AddressEntity> addressEntities = new LinkedList<>();
    AddressEntity addressEntity = new AddressEntity();
    addressEntity.setId(1);
    addressEntities.add(address);
    personEntity.setAddresses(addressEntities);
    reactiveEntityStore.insert(personEntity).blockingGet();

    //This will cause the row to be inserted in the join table
    address.getPersons().add(personEntity);
    reactiveEntityStore.update(address).blockingGet();
```

Thanks & regards

**Comment by npurushe** [comment] 2017-01-03 01:43
Hi, did you manually add `setPersons` and `setAddresses` to your entity? these aren't generated by requery. You should not overwrite the collection field with another collection, your example should be something like this.

```java
Address address = new AddressEntity();
// set address properties
Person person = new PersonEntity();
// set person properties
address.getPersons().add(person);
store.insert(address).blockingGet();
```

Basically you shouldn't set the collection value, rather just add/remove/clear items from it. Hope that makes sense, thanks

**Comment by Agraphie** [comment] 2017-01-03 08:15
Hi,

thanks for the reply. That makes sense, however, I'm using Jackson to parse JSON to an entity in my use case (I guess that's pretty common right?). Looking at the entity, the collection get instantiated correctly (so it's not empty) but as I said, not saved. I guess because Jackson is overwriting the collection?
If the only way is to add/remove/clear values, then how would it work with any JSON library?

**Comment by npurushe** [comment] 2017-01-03 21:17
Are you using Jackson databind? This maybe happening because Jackson doesn't find the setter for the collection. Also does your json actually contain a collection that would map to it? The best solution is really to have Jackson ignore the relational collection and populate this collection in your application code.

**Comment by Agraphie** [comment] 2017-01-03 21:26
I'm only using Jackson Databind Threetenbp. Yes the json contains objects which would map correctly.

So for the previous example, the JSON for a person would contain a collection containing Address objects. As I'm using the same IDs as in the backend, they match as well. I also tried to explicitely selecting every Address on the device and setting the received Address object to that, without success.

I could do the same and then call `add` for every object (as you suggested). But that means that whenever there is a many to many relation and I receive a collection from the backend, I need to always iterate and select every single entity (from the devices's DB) and add it manually. Yet this seems like a dirty fix to me?

**Comment by npurushe** [comment] 2017-01-03 21:53
Thanks for the explanation that helps. I think the main problem here would be making sure duplicate entries in join table aren't created. The problem with overwriting the collection is that requery doesn't know which of those entities are in the database or not, and if there is ManyToMany relationship between the objects already or not, as this state is stored in the collection. I will reopen and look into a better solution for this.

**Comment by Agraphie** [comment] 2017-01-03 22:00
Cheers for that. For the first problem (are the entities already in the database?), I think it would be fine to just throw a foreign key exception if at least one of them is not, no? For the second, I don't really know... Let me know if I can help you.

**Comment by kaladivo** [comment] 2017-01-06 18:06
Hi, I still don't get any addresses when executing upper code:
```
Address address = new Address();
Person person = new Person();

address.getPersons().add(person);
Application.getDataStore().insert(address);

Person result = Application.getDataStore().select(Person.class).get().first();
```
 `result.getAddresses()` still returns an empty collection. Am I doing something wrong?

**Comment by Agraphie** [comment] 2017-01-06 20:29
I can also confirm what @kaladivo said. However, executing this (based on @kaladivo code) works:
```Java
Address resultAddress = reactiveEntityStore.select(AddressEntity.class).get().first();
resultAddress.getPersons();
```

**Comment by npurushe** [comment] 2017-01-10 07:58
@kaladivo What's your datastore type? if it's one of the async wrappers for EntityDataStore then you maybe ignoring the return type. which for something like RxJava needs to be subscribed to in order to complete

**Comment by Agraphie** [comment] 2017-01-20 19:40
As this is a bit of a blocker for me, would it be possible to somehow reinstantiate the state of the collection? After Jackson parsed the JSON to the object, the collection is filled up but the state for this collection is `null` (in the example above, `$persons_state=null`). As requery is not generating the setter for such field, would it be possible for requery to generate the setter and then instantiate/modify the state in it?

**Comment by kaladivo** [comment] 2017-01-20 20:03
@npurushe This is how I create datastore:
```
DatabaseSource source = new DatabaseSource(this, Models.DEFAULT, 16);
Configuration configuration = source.getConfiguration();
dataStore = new EntityDataStore<Persistable>(configuration);
```

Sorry for late anwser...

**Comment by Agraphie** [comment] 2017-01-21 11:56
I have also tried (Jackson specific) to use the setter like this
```Java
 @JsonSetter
  public void setPersons(List<PersonEntity> personEntities) {
    if (persons== null) {
      persons = new LinkedList<>();
    }
    persons.addAll(personEntities);
  }
```

This works fine at first and the person state is not `null`, (but `modofied`) when the entity initialised. However, later upon saving, the person state is `null` again. Just as workaround, at what stage would I have to call `addAll` so that the state does not get set to `null`?

**Comment by npurushe** [comment] 2017-01-23 05:45
Sorry for the late update. Right now only the fields of an entity that map to columns of should be serialized through jackson/gson. Serializing relational links e.g. OneToMany should be done manually because a) they are circular referencing (the relation will also refer back to the original object so would need to be skipped or handled differently) and b) they need a special collection type in order to track changes to the collection.

I understand it's convenient to try to do some of this through jackson databind. So will work on a Jackson Module that works with requery generated entities/collections but it is unlikely it will solve all json use cases.

**Comment by Agraphie** [comment] 2017-01-23 08:26
Hi, thanks for the update. I don't mind doing it manually, but my approach right now is 
1. get all entities from backend via json (400+ entities)
2. save all entities and return them
3. iterate through all saved entities and add (via `add()`) the many-to-many collection manually (e.g. `persons` above)
4. save the modified entities

Unfortunately this is not very performant, although I'm looking into ways top optimise it. Can we just instantiate this special collection somehow? If we customise the deserialiser of jackson (or use the `@JsonSetter` like above) and instantiate the special collection there, wouldn't it solve the problem? Not generic, but at least a good workaround.

Thanks for your help.

**Comment by Agraphie** [comment] 2017-02-03 10:13
For everyone stumbling upon this, inspired by #73 and [stackoverflow](https://stackoverflow.com/questions/6834677/jackson-mapper-post-construct) I came up with the following workaround:

```Java
public class PersonEntityConverter extends StdConverter<PersonEntity, PersonEntity> {

  @Override
  public PersonEntityConvert(PersonEntity value) {
    for (Attribute<PersonEntity, ?> attr : PersonEntity.$TYPE.getAttributes()) {
      if (attr.getCardinality() == null || attr.getCardinality().equals(Cardinality.ONE_TO_ONE) || attr.getCardinality().equals(Cardinality.MANY_TO_ONE)) {
        continue;
      }
      attr.getPropertyState().set(value, PropertyState.MODIFIED);
    }
    return value;
  }
}
```

The `PersonEntity` class can then be annotated with `@JsonDeserialize(converter = PersonEntityConvert.class)`.
This has the advantage that I'm not interfering with any deserialisation/serialisatione (better compatible to future updates) and I'm only touching the necessary things.

However, I think a solution would be required how we can make this converter abstract and then (maybe?) distribute it with the library.

**Comment by npurushe** [comment] 2017-02-04 20:32
Ultimately converters aren't enough to do this correctly. It requires a custom Jackson module. 

There is now a requery jackson module with a custom mapper `EntityMapper`. It supports requery annotations automatically applying jackson forward and backward references (`JsonManagedReference`/`JsonBackReference`). Automatic lookup of entity objects by id during deserialization (Note the key field must be first in the json). This should solve most common types of json serialization problems. It will be released in the next update but the code is in master as of now.

**Closed by npurushe** 2017-02-04 20:32 UTC
Labels: enhancement

**Comment by Agraphie** [comment] 2017-02-05 18:24
Thanks for your amazing work! I have checked out the current master and tried it with our project. Unfortunately I got ` java.lang.NoSuchFieldException: No field id in class  ...` and I assume this is because the field "id" is specified in a parent (abstract) class which is extended by a specific class.
Everything else should be as you described, `id` is the first field in the received JSON and even the first field in the specific classes.

**Comment by npurushe** [comment] 2017-02-05 18:40
Do you have the full stack trace from the error? probably should be easy to fix.

**Comment by Agraphie** [comment] 2017-02-05 18:50
I actually got rid of it by just using a helper method in `EntityAnnotationIntrospector` which searches in the parent classes as well (inspired by [Apache](https://commons.apache.org/proper/commons-lang/apidocs/src-html/org/apache/commons/lang3/reflect/FieldUtils.html)

```Java
private Field getFieldFromClass(final Class<?> cls, final String fieldName) throws NoSuchFieldException {
        Field result = null;
        for (Class<?> acls = cls; acls != null; acls = acls.getSuperclass()) {
            try {
                result = acls.getDeclaredField(fieldName);
            } catch (final NoSuchFieldException ex) {
                // ignore
            }
        }

        if (result == null) {
            throw new NoSuchFieldException(fieldName);
        }
        return result;
    }
```

However, I get a second error with just the stacktrace
```Java
java.lang.Exception: com.fasterxml.jackson.databind.JsonMappingException: Multiple back-reference properties with name 'null'
                                                                                                      at [Source: okhttp3.ResponseBody$BomAwareReader@d6b9071; line: 1, column: 1]
```
But I have not looked into it.

**Comment by lewinskimaciej** [comment] 2017-02-06 14:12
Is there a way to make it work with data, that has no Id in json and it is @Generated? I'm currently having issue with this approach:
```java
public abstract class AbstractItem implements Parcelable, Persistable {
    @Key
    @JsonProperty("id")
    long id;

    @JsonProperty("name")
    String name;

    @OneToMany(mappedBy = "item", cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    @JsonProperty("subItems")
    List<SubItem> subItems;
}

public abstract class AbstractSubItem implements Parcelable, Persistable {
    @Key
    @Generated
    @JsonProperty("id")
    long id;  // this one is not from json, it's generated

    @JsonProperty("something")
    int something;

    @ManyToOne(cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    Item item;
}
```

The problem is, that SubItem has no ID from API, in this case, the subItems list doesn't even get populated.
I've manually copied all the classes for the Jackson Module for now(until release) and I'm using it like this:
```java
ObjectMapper objectMapper = new EntityMapper(Models.DEFAULT, dataStore);
        objectMapper.registerModule(new JodaModule())
                .writerWithDefaultPrettyPrinter();
        objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true)
                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

...

Retrofit.Builder()
                .addConverterFactory(JacksonConverterFactory.create(objectMapper))
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .baseUrl(baseUrl)
                .client(okHttpClient)
                .build();
```
When I manually add @JsonManagedReference and @JsonBackReference, the list get's populated, but it doesn't save with insert/upsert. Anything I can do with it or should I just manually add subItems to the list after Inserting and then update? Or am I doing something wrong?

**Comment by npurushe** [comment] 2017-02-07 03:09
If the data is in the collection it should get inserted on an update/insert. What api are you using when you have the problem `EntityStore.update` ? 

The problem with not having an id is that any existing SubItem could never be updated during deserialization, only additional ones inserted. In case like that maybe you want to delete all the existing subItems, this something that can be improved but there are lot of edge cases to consider in that kind of scenario.

**Comment by lewinskimaciej** [comment] 2017-02-07 08:54
I'm using ReactiveEntityStore<Persistable> and upserting the Model I got through Retrofit(parsed with requery-jackson module as seen above). Initial upsert won't save subItems, I have to manually go through the list in a loop after upsert and .add() them to the list then update. Model that comes from API does not have ID's for subItems, I'd like them to generate automatically while parsing. At least that seems to me like it's supposed to work like that, as in most cases models coming from API won't have ID's for every subItem.
