### ISSUE TITLE
Consider annotations on the base class/interface

### ISSUE THREAD

**Issue by RoRoche** [requery/requery#61] opened 2016-03-29 09:34 UTC
Is it possible to annotate the base class/interface with some libraries (Jackson, LoganSquare, [android-transformer](https://github.com/txusballesteros/android-transformer/), etc.) and to copy these annotations to the generated class?

For example, here is a base class annotated with android-transformer:

```java
@Mappable( with = AnotherPersonType.class )
@Entity
abstract class AbstractPerson {

    @Mapped
    @Key @Generated
    int id;

	@Mapped ( toField = "theName")
    @Index(name = "name_index")
    String name;
}
```

Is there a way to get my `Person` class generated with these android-transformer's annotations?

**Comment by npurushe** [comment] 2016-03-29 14:43
Hi in a case like that the annotations are still there the generated class is just extending AbstractPerson. 
Jackson databind should work fine because you can just pass in the generated class type (Person.class) into the mapper API. 

The issue with LoganSquare is that it creates an instance of the annotated class in it's JsonObjectMapper, the problem is that it is not configurable to provide a derived class there. Might be worth asking them for a way to customize that. For instance [Parceler](https://github.com/johncarl81/parceler) allows you to have a @ParcelFactory to provide the instance, it would need to support something like that. I will look into android-transformer haven't used it before.

**Comment by npurushe** [comment] 2016-05-23 01:19
Closing for now since this depends on the other libraries for supporting extendable classes / interfaces

**Closed by npurushe** 2016-05-23 01:19 UTC
Labels: enhancement
