### ISSUE TITLE
unable to open database file (code 2062)

### ISSUE THREAD

**Issue by k0shk0sh** [requery/requery#546] opened 2017-05-01 05:30 UTC
Hi there, 
Thanks for the wonderful library, I have this bug reported in firebase 38 times as below: 

```
Caused by java.sql.SQLNonTransientException: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062) ################################################################# Error Code : 2062 (SQLITE_CANTOPEN_EMFILE) Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default. (unable to open database file (code 2062)) #################################################################
io.requery.android.sqlite.BaseConnection.throwSQLException (BaseConnection.java:75)
io.requery.android.sqlite.SqliteStatement.executeQuery (SqliteStatement.java:70)
io.requery.sql.SelectResult.iterator (SelectResult.java:103)
io.requery.query.BaseResult.iterator (BaseResult.java:121)
io.requery.query.BaseResult.firstOr (BaseResult.java:92)
io.requery.query.BaseResult.firstOrNull (BaseResult.java:112)
io.requery.query.ResultDelegate.firstOrNull (ResultDelegate.java:79)
com.fastaccess.data.dao.model.AbstractLogin.getUser (AbstractLogin.java:66)
com.fastaccess.provider.tasks.notification.NotificationSchedulerJobTask.onStartJob (NotificationSchedulerJobTask.java:49)
android.app.job.JobService$JobHandler.handleMessage (JobService.java:143)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6692)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
```
Can't really tell what's going on but I guess it could be due to the fact that cursor was never closed or left open somewhere. 

the method that causes this is: 

```
public static Login getUser() {
    return App.getInstance().getDataStore()
            .select(Login.class)
            .where(Login.LOGIN.notNull()
                    .and(Login.TOKEN.notNull()))
            .get()
            .firstOrNull();
}
```

and its being called from a service to determine if the user is logged-in or no.

**Comment by consp1racy** [comment] 2017-05-01 07:16
How do you initilaize DataStore?

**Comment by k0shk0sh** [comment] 2017-05-01 07:18
@consp1racy as below

```
 public SingleEntityStore<Persistable> getDataStore() {
    if (dataStore == null) {
        EntityModel model = Models.DEFAULT;
        DatabaseSource source = new DatabaseSource(this, model, "FastHub-DB", 7);
        Configuration configuration = source.getConfiguration();
        if (BuildConfig.DEBUG) {
            source.setTableCreationMode(TableCreationMode.CREATE_NOT_EXISTS);
        }
        dataStore = RxSupport.toReactiveStore(new EntityDataStore<Persistable>(configuration));
    }
    return dataStore;
}
```

**Comment by k0shk0sh** [comment] 2017-05-01 07:22
To be honest, I myself, using the app almost every 10 minutes never encountered this, however I'm seeing plenty of crashes regards `requery` in firebase.

**Comment by npurushe** [comment] 2017-05-04 03:00
This can happen if lots of queries are made without closing them. That is you may want to add try-with-resources or manually call close on all query operations returning `Result`. Normally the cursor is closed if you use a terminating operator like `firstOrNull` or `toList`, but for example if you just iterate a `Result` instance with a normal for-each loop then you may want to close it manually.

**Closed by npurushe** 2017-05-04 03:00 UTC

**Comment by k0shk0sh** [comment] 2017-05-04 03:05
@npurushe people reports that it happens when app starts, and the first thing happens when app starts is the method I showed in my previous comment which has `firstOrNull` I'm abit confused here.

**Comment by novjean** [comment] 2019-01-29 20:07
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened too many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:904)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.delete(SQLiteDatabase.java:1932)
       at beg.a(:com.google.android.gms.dynamite_dynamitemodulesc@14799050@14.7.99 (040406-223214910):38)
       at bev.run(:com.google.android.gms.dynamite_dynamitemodulesc@14799050@14.7.99 (040406-223214910):20)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
