### ISSUE TITLE
How does toSelfObservable work?

### ISSUE THREAD

**Issue by Pr0bability** [requery/requery#94] opened 2016-04-16 17:33 UTC
Hello,

I have a question about how toSelfObservable works. I gather it should react to database changes on the given table, but what exactly does it return? Only the changed data? The whole table?

Thank you.

**Comment by npurushe** [comment] 2016-04-16 17:44
It returns an Observable of the type [Result](http://requery.github.io/javadoc/io/requery/query/Result.html). The observable will be triggered on any entity operation could affect that result type. An example would be if you have query that lists some elements, then somewhere else in your code you modify/insert/delete elements. That would cause the observable to emit the Result and now you can re-run the query and get the changes. It's useful for saying updating a UI when you change your data from a background operation.

**Comment by Pr0bability** [comment] 2016-04-16 17:47
Yes, that's what I have gathered. Let me explain my situation. I have a list of events in the database. Every event has a particular status, and I am interested in only those of a certain status (three different statuses to be exact). Now I want to react when the table of events gets updated. Right now, it seems that the self observable I have returns only those elements that changed in the result Result (in the Observable). Is that the case?

**Comment by npurushe** [comment] 2016-04-16 17:55
It is linked to the original query you made. So you if have 
```java
data.select(Event.class).where(Event.STATUS.eq("something")).toSelfObservable().subscribe(
  new Action1<Result<Event>>() {
                public void call(Result<Event> persons) {
                    // result matching the query
                }
            });
``` 
The result in the subscription would be the same as if you called 
```java 
data.select(Event.class).where(Event.STATUS.eq("something")).get()
```

**Comment by Pr0bability** [comment] 2016-04-16 18:12
The query I have is the following:

`public Observable<Result<HistoryEvent>> getActiveHistoryEvents() {
        return mDb.select(HistoryEvent.class)
                .where(HistoryEventEntity.STATUS.eq(HistoryEvent.STATUS_PENDING))
                .or(HistoryEventEntity.STATUS.eq(HistoryEvent.STATUS_UNRESOLVED))
                .or(HistoryEventEntity.STATUS.eq(HistoryEvent.STATUS_PENDING_POSTPONED))
                .get()
                .toSelfObservable();
    }`

The thing is, the Log I have in the getTimeline subscription keeps saying things like 1 or 2, even though when I go to another fragment in the viewpager (destroying the original one in the process), and back into the one with the list (so that getTimeline gets called again), it logs the supposedly correct number.

**Comment by npurushe** [comment] 2016-04-16 18:18
What is the value you are expecting? One thing to try is to make the query regularly after making a change and check the results, then also log the output of running the query from the Observable subscription, do you get differing results?

**Comment by Pr0bability** [comment] 2016-04-16 18:25
I am expecting to get all the active history events as far as the query goes, but it seems I only get one event, which is weird. Every pending event has a notification associated to it, and a pending event is supposed to change to unresolved as soon as the notification goes off creating a new pending event in the process. I want to update the list in the RecyclerView so that it correctly has both the unresolved event and the pending event (and the list of the upcoming events that are not saved in the db, generated by loadTimeline in the first code I posted).

When calling getActiveHistoryEvents right after changing the status and creating new pending event, it displays the correct amount when logging the size. But the self observable updating the list gets called multiple times (I guess on the status change, then on the new pending event), with sizes of 2 and then 1.

**Comment by npurushe** [comment] 2016-04-16 18:31
If you are making several changes, trying running them in a single transaction with runInTransaction, then you will only get one Observable update after you commit your changes. I think that maybe why it's not matching what you're expecting.

**Comment by Pr0bability** [comment] 2016-04-16 18:49
The thing is, the changes happen at multiple places, how would I go about implementing it the runInTrasaction way?

**Comment by npurushe** [comment] 2016-04-17 19:38
If you're performing multiple update operations you can group those in a runInTransacton block, but even if not that is ok. You should receive all the notifications in order that you make them. Can you try again with the beta15 version? Made some changes there to the way the updates are published that may help on this issue.

**Comment by Pr0bability** [comment] 2016-04-17 20:35
I have gone around the issue by reacting on the table update by making another query for the whole table. But with beta15 it seems that even the original version should work, great job!

I have another issue that is connected to inserting stuff into the database and observing on this insert, I will open thread.

**Comment by npurushe** [comment] 2016-04-20 03:19
Closing this one since it seems the issue is covered

**Closed by npurushe** 2016-04-20 03:19 UTC
Labels: question
