### ISSUE TITLE
Error deserializing Entity classes with Gson

### ISSUE THREAD

**Issue by austynmahoney** [requery/requery#73] opened 2016-04-05 01:17 UTC
I'm getting an error when I desieralize JSON into my entity classes using Gson. My app fails with a JNI error that says 

```
JNI DETECTED ERROR IN APPLICATION: can't make objects of type com.-redacted-.model.requery.RequeryUser: 0x12e84980
```

I have a top level `RequeryFeedItem` that is composed of a `RequeryUser` (I am required to use interfaces because I am binding them to layouts using Android Databinding.). The API returns `List<RequeryFeedItem>`, so that is what I am trying to deserialize.

``` java
@Entity("FeedItemEntity")
public interface RequeryFeedItem {
    @ForeignKey
    @ManyToOne(cascade = {CascadeAction.DELETE, CascadeAction.SAVE})
    RequeryUser getOwner();
}
```

``` java
@Entity(name = "UserEntity")
public interface RequeryUser {
    @Key
    String getId();
}
```

@KrzysztofWrobel @npurushe Do either of you have any tips for fixing this issue when integrating Requery with Gson?

**Comment by npurushe** [comment] 2016-04-05 03:10
That's probably because it's an interface and gson cannot instantiate it. You can the built in gson [RuntimeTypeAdapterFactory](https://github.com/google/gson/blob/master/extras/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java) to provide implementations of it.

**Comment by KrzysztofWrobel** [comment] 2016-04-14 17:59
Heyah,

I didn't have time to figure out better solution, so I have ended up with writing JsonDeserializers for all of my entities. In order to store it properly with Requery I had to mark all properties as Modified with this "hacky" block of code.

Hope it can help you @austynmahoney :)
```
public class ClimbingProblemDeserializer implements JsonDeserializer<ClimbingProblem> {
    @Override
    public ClimbingProblem deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        JsonObject ja = json.getAsJsonObject();
        ClimbingProblemEntity climbingProblem = context.deserialize(ja, ClimbingProblemEntity.class);
        //TODO hack to indicate to requery that GSON objects has to be updated
        for (Attribute<ClimbingProblemEntity, ?> attr : ClimbingProblemEntity.$TYPE.attributes()) {
            attr.propertyState().set(climbingProblem, PropertyState.MODIFIED);
        }

        return climbingProblem;
    }
}
```

**Comment by npurushe** [comment] 2016-04-15 03:36
Thanks for posting your solution. Have you tried setting the `stateless` property of `@Entity` to true? this will remove the tracked state in the generated code, the downside of this is that on every update operation all fields will updated/inserted

**Comment by KrzysztofWrobel** [comment] 2016-04-15 16:56
No, I haven't. But I will give it a try:) Thanks for suggesting.

**Comment by austynmahoney** [comment] 2016-04-18 16:31
Thanks for the info @KrzysztofWrobel.

Creating custom deserializers/serializers for every entity in my app is not a road I would like to go down though. For me, It defeats the entire point of a library like Gson.

**Comment by npurushe** [comment] 2016-04-19 02:55
I think the adapter from @KrzysztofWrobel can also be made generic for any type. However I think `@Entity(stateless=true)` should cover this case as well. Let me know if not.

**Comment by KrzysztofWrobel** [comment] 2016-04-19 10:01
Exactly as @npurushe says. I've changed my entities to stateless and was able to remove those deserializers. Also in my case I'm not annotating interfaces like you in your example but abstract classes. 
That allows me to combine Requery with GSON annotations like @SerializedName and @Expose. 
To sum it up, Gson is fully compatible with Requery, but it requires to take this specific approach to make it work.

**Comment by tsunamilx** [comment] 2016-05-03 02:58
I found `stateless = true` seems to be buggy, see issue #122 .

But I just realize that with `stateless = false`, GSON can still work, just use concrete class for relationships instead of abstract class or interface.

**Comment by Mark-William-Schumacher** [comment] 2016-05-24 14:36
Can we get an explicit example of how to do this, or a better resource on how to do this. This is a huge deal for how I intend on using the library.

**Comment by npurushe** [comment] 2016-05-26 04:39
Yes a test model using gson will be added to cover these cases

**Comment by Glurt** [comment] 2016-06-13 14:25
If my now stateless Entity contains a JunctionTable definition, does this also need to be stateless?

I'm currently getting a NPE on EntityWriter:691 because proxy.get(attribute, false) returns null.

**Comment by npurushe** [comment] 2016-06-15 01:09
Thanks for reporting the value was passed to the many-to-many join entity, will be fixed in the next update

**Comment by colintheshots** [comment] 2016-12-07 17:05
Could we come up with a generalized code approach to this problem or something to assist with conversion? @KrzysztofWrobel had a decent solution, but it requires too much boilerplate to be the official fix. Serialization is core to most apps these days. There should be a better option.

**Comment by colintheshots** [comment] 2016-12-08 17:03
@KrzysztofWrobel How did you get Gson to work for OneToMany without custom deserializers (and with stateless=true)? I get "Can't instantiate abstract class" because it wants to instantiate the abstract class instead of the generated entity class.

**Comment by npurushe** [comment] 2016-12-08 17:18
This something still being looked into. The fundamental problem is Gson uses reflection modify the private fields of an object and there is simply no way to tell what changes it made, without duplicating all fields of the object and comparing them. Other serialization json frameworks like Jackson databind can properly use the setters of an object to modify them and will work fine.

**Comment by colintheshots** [comment] 2016-12-08 19:13
I'm seeing the same error with Jackson on instantiating a serialized object in a OneToMany relationship as List<Pojo>.

com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.stackpath.cloak.model.Target, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information

**Comment by npurushe** [comment] 2016-12-09 06:35
Do you have the full stacktrace? which object couldn't be constructed?

**Comment by colintheshots** [comment] 2016-12-09 15:26
It happens when I use an abstract class for deserialization. If I change it to be non-abstract, deserialization works.

Here's the stack trace:

`com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.fake.Device, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
                                          at [Source: java.io.InputStreamReader@8750511; line: 1, column: 12] (through reference chain: com.fake.Response["device"])
                                          at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:908)
                                          at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:150)
                                          at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
                                          at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
                                          at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
                                          at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
                                          at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1575)
                                          at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1183)
                                          at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:32)
                                          at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
                                          at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
                                          at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                                          at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                          at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
                                          at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
                                          at rx.Subscriber.setProducer(Subscriber.java:211)
                                          at rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
                                          at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
                                          at rx.Subscriber.setProducer(Subscriber.java:205)
                                          at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                          at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
                                          at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                          at rx.Observable.unsafeSubscribe(Observable.java:8666)
                                          at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                          at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:220)
                                          at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                          at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                          at java.lang.Thread.run(Thread.java:761)`

**Comment by colintheshots** [comment] 2016-12-13 21:13
FYI. I solved the issue from my previous comment by adding @JsonDeserialize(as = DeviceEntity.class) on the Device class.

I did run into another problem with @OneToMany relations not persisting from one SELECT to the next, but I'll open a new issue for that if I find it's not a bug hidden in my code.

**Comment by AlexeyKorshun** [comment] 2017-01-25 17:49
Good day, I try to save data from gson

First entity:
`@Entity(stateless = true)
abstract class AbstractTeam implements Parcelable, Persistable {

    @Key
    int id;

    @SerializedName("head_coach")
    @ForeignKey
    @OneToOne
    HeadCoach coach;

    String name;
}`

Second entity:
`@Entity(stateless = true)
abstract class AbstractHeadCoach implements Parcelable, Persistable {

    @Key
    @Generated
    int id;

    @Column(unique = true)
    String name;
    String photo;

}`

But I have issue:

`01-25 23:47:57.506 4728-4728/com.rosberry.android.khlstats E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                             Process: com.rosberry.android.khlstats, PID: 4678
                                                                             io.requery.sql.StatementExecutionException: Exception executing statement: insert into Team (id, coach, name) values (?, ?, ?)
                                                                                 at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:59)
                                                                                 at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40)
                                                                                 at io.requery.query.BaseScalar.value(BaseScalar.java:48)
                                                                                 at io.requery.sql.EntityWriter.insert(EntityWriter.java:439)
                                                                                 at io.requery.sql.EntityWriter.upsert(EntityWriter.java:483)
                                                                                 at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:280)
                                                                                 at io.requery.reactivex.WrappedEntityStore$8.call(WrappedEntityStore.java:138)
                                                                                 at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35)
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656)
                                                                                 at io.reactivex.internal.operators.completable.CompletableFromSingle.subscribeActual(CompletableFromSingle.java:29)
                                                                                 at io.reactivex.Completable.subscribe(Completable.java:1613)
                                                                                 at io.reactivex.Completable.subscribe(Completable.java:1601)
                                                                                 at com.rosberry.android.khlstats.data.DataRepositoryImpl.lambda$getTeam$0(DataRepositoryImpl.java:30)
                                                                                 at com.rosberry.android.khlstats.data.DataRepositoryImpl$$Lambda$4.accept(Unknown Source)
                                                                                 at io.reactivex.internal.operators.single.SingleDoOnSuccess$1.onSuccess(SingleDoOnSuccess.java:44)
                                                                                 at io.reactivex.internal.operators.single.SingleMap$1.onSuccess(SingleMap.java:50)
                                                                                 at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111)
                                                                                 at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
                                                                                 at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:47)
                                                                                 at io.reactivex.Observable.subscribe(Observable.java:10514)
                                                                                 at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                                 at io.reactivex.Observable.subscribe(Observable.java:10514)
                                                                                 at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656)
                                                                                 at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33)
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656)
                                                                                 at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656)
                                                                                 at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                                 at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                 at java.lang.Thread.run(Thread.java:818)
                                                                              Caused by: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
                                                                                 at io.requery.android.sqlite.BaseConnection.throwSQLException(BaseConnection.java:69)
                                                                                 at io.requery.android.sqlite.SqlitePreparedStatement.executeUpdate(SqlitePreparedStatement.java:170)
                                                                                 at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:54)
                                                                                 at io.requery.sql.EntityUpdateOperation$1.evaluate(EntityUpdateOperation.java:40) 
                                                                                 at io.requery.query.BaseScalar.value(BaseScalar.java:48) 
                                                                                 at io.requery.sql.EntityWriter.insert(EntityWriter.java:439) 
                                                                                 at io.requery.sql.EntityWriter.upsert(EntityWriter.java:483) 
                                                                                 at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:280) 
                                                                                 at io.requery.reactivex.WrappedEntityStore$8.call(WrappedEntityStore.java:138) 
                                                                                 at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:35) 
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656) 
                                                                                 at io.reactivex.internal.operators.completable.CompletableFromSingle.subscribeActual(CompletableFromSingle.java:29) 
                                                                                 at io.reactivex.Completable.subscribe(Completable.java:1613) 
                                                                                 at io.reactivex.Completable.subscribe(Completable.java:1601) 
                                                                                 at com.rosberry.android.khlstats.data.DataRepositoryImpl.lambda$getTeam$0(DataRepositoryImpl.java:30) 
                                                                                 at com.rosberry.android.khlstats.data.DataRepositoryImpl$$Lambda$4.accept(Unknown Source) 
                                                                                 at io.reactivex.internal.operators.single.SingleDoOnSuccess$1.onSuccess(SingleDoOnSuccess.java:44) 
                                                                                 at io.reactivex.internal.operators.single.SingleMap$1.onSuccess(SingleMap.java:50) 
                                                                                 at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111) 
                                                                                 at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66) 
                                                                                 at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:47) 
                                                                                 at io.reactivex.Observable.subscribe(Observable.java:10514) 
                                                                                 at com.jakewharton.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34) 
                                                                                 at io.reactivex.Observable.subscribe(Observable.java:10514) 
                                                                                 at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) 
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656) 
                                                                                 at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:33) 
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656) 
                                                                                 at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35) 
                                                                                 at io.reactivex.Single.subscribe(Single.java:2656) 
                                                                                 at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) 
                                                                                 at io.reactivex.Scheduler$1.run(Scheduler.java:134) 
                                                                                 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59) 
                                                                                 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51) 
                                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                 at java.lang.Thread.run(Thread.java:818) 
                                                                              Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
                                                                                 at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
                                                                                 at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
`

**Comment by npurushe** [comment] 2017-02-04 20:37
Unfortunately the Gson API is too limited and doesn't support customization of the serialization process, additionally the development of gson features doesn't appear to be active so it's unlikely they would support using getter/setters. Jackson however supports this as well as serializing graph based references.

In the next update there will be a requery jackson module with a custom mapper `EntityMapper`. It supports requery annotations automatically applying jackson forward and backward references (`JsonManagedReference`/`JsonBackReference`). Automatic lookup of entity objects by id during deserialization (Note the key field must be first in the json). This should solve most common types of json serialization problems.

**Closed by npurushe** 2017-02-04 20:37 UTC
Labels: enhancement, question
