### ISSUE TITLE
Update is not triggered

### ISSUE THREAD

**Issue by Pedramrn** [requery/requery#520] opened 2017-04-19 14:37 UTC
I created a repository to showcase the behavior I have encountered.
https://github.com/Pedramrn/requery-bug

I couldn't reproduce the bug with a simple activity setup, it's a strip down version of a project that I'm working on.

It's a 2 page app, any change from second page should cause an update in a first page. the strange behavior is, the update will receive if the second page register an update listener too.

**Comment by npurushe** [comment] 2017-04-19 15:27
Thanks for the example will take a look. Is this issue similar to #511 ?

**Comment by maxxx** [comment] 2017-05-02 08:30
I have also noticed a bug with update and relations, but looks like not similar to these 2 issues.
First entity has
```
	@ManyToMany
	@JunctionTable
	List<SecondEntity> getList();
```
Second entity has similar @ManyToMany, nothing special.
Bug appears when using upsert method. For example we have in db firstEntity (id=1) with linked first secondEntity (id=1). Then we creating new firstEntity (with same primary id), adding secondEntity with id =2 to list, and doing upsert. In conclusion i got 2 bugs:
1) if using observableResult() there is update call, but received entity has old getList() content, not updated one
2) after app restart there is 2 rows in relation table and getList() contains 2 secondEntites (id=1 and id=2)
I tried to replace upsert code with delete + insert and both bugs gone away.

**Comment by npurushe** [comment] 2017-05-08 07:37
This should be resolved in 1.3.2 with the fix from #548

**Comment by Pedramrn** [comment] 2017-05-08 07:52
@npurushe The issue has not resolved in 1.3.2, you can check the sample project.

**Comment by npurushe** [comment] 2017-05-10 15:31
I tried your example your second page doesn't appear to be wired up to update based on anything, however the database change notification is triggered.

**Comment by Pedramrn** [comment] 2017-05-10 16:26
No, the second page is just for causing an update to database.

The first page listens for updates.
Any change from second page should trigger and update in first page.

**Comment by npurushe** [comment] 2017-05-12 07:50
Currently observable changes aren't triggered from update queries just entity updates which is why it doesn't fire in that case. However that seems easy to add support for.

**Comment by npurushe** [comment] 2017-05-15 06:23
This is actually working as intended from the changes from #168 your example isn't working because the entity store is created multiple times (https://github.com/Pedramrn/requery-bug/blob/master/app/src/main/java/com/github/pedramrn/requerybug/di/AppModule.java#L40) 

these instances will not know about each other and hence not be able to generate the change notifications across instances, this should be made a singleton instead to resolve the problem.

**Closed by npurushe** 2017-05-15 06:23 UTC
