### ISSUE TITLE
Add support for new KAPT 1.0.4

### ISSUE THREAD

**Issue by consp1racy** [requery/requery#296] opened 2016-10-10 10:59 UTC
Entity and model classes are not generated.

See https://blog.jetbrains.com/kotlin/2016/09/kotlin-1-0-4-is-here/

**Comment by npurushe** [comment] 2016-10-11 06:12
This is still marked as experimental in Kotlin, once it's working properly it shouldn't require any changes from annotation processors like requery to work correctly.

**Comment by NeverwinterMoon** [comment] 2016-12-27 09:27
Sorry if I am overdoing it, but going to repeat what I said at #385 here as well (as it was closed): kapt2 is definitely working with other annotation processing libraries: I've been using it development (and shipped to production) with Dagger 2 (at least version 2.8 of it), so the issue is definitely not in kapt2 alone.

**Comment by consp1racy** [comment] 2016-12-27 22:35
> ### Kapt Improvements
> We continue to work on the experimental version of Kotlin annotation processing tool (kapt). While there are still some things to do in order to fully support incremental compilation, performance of the annotation processing is significantly increased since Kotlin 1.0.4.
>
> To enable experimental kapt, just add the following line to your build.gradle:
>
> `apply plugin: 'kotlin-kapt'`

Source: [Kotlin 1.0.6 is here!](https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-0-6-is-here/)

**Closed** 2016-12-29 06:45 UTC
Labels: enhancement

**Comment by npurushe** [comment] 2016-12-29 07:31
The 1.0.6 version has enough fixes to make it stable. However it doesn't pass the kapt.annotations property to the processor, so the processor has been updated to handle that. However since it's still considered experimental, the original kapt is still the preferred option until that changes. thanks
